### ISSUE TITLE
Idea for execution time + maybe progress reporting if possible

### ISSUE THREAD

**Issue by rphair** [pixelsoup42/cardano_account_pandas_dumper#4]
Thanks @pixelsoup42 for providing this tool which I still use every now & then... sorry I could not have been of more help getting it approved for the Developer Portal.

I still stand by my own use case of getting a wallet dump from a stake key, but in the long time since I used it last it takes (under whatever conditions I have, likely network + API response times) a bit longer to run: currently 7½ minutes for a modestly used stake key with less than a half-dozen transactions a month.

Twice I ran it & interrupted thinking it was hanging, before thinking that perhaps chain size increase or free tier API delays might have drawn out the time a bit.  Other users might not think of doing this... so to help people get comfortable with your tool I thought a note in the `README.md` to explain long wait times and help to account for these would help set their expectations.

If you are still interested in maintaining this (you would have my appreciation for doing so), I think a comprehensive improvement would be to offer some "progress" indication (text only would be fine, and rough would be better than nothing) perhaps by the percentage of where the tool is scanning relative to the tip of the chain.  (That's assuming the data fetch isn't always accomplished in a single API query of course... apologies for not being familiar with your implementation.)

**Comment by pixelsoup42** [comment]
Hi @rphair , thanks for your feedback !

I think the problem of rate-limiting is already kind of covered in the README.md:

```
If you get a [blockfrost.io](https://blockfrost.io/) API error, or if execution is very slow, please see the blockfrost_project_id command line flag below.
```

**Comment by deedf** [comment]
I will close this issue for now as there are too few users to justify investing time in this tool.

If more people chime in (I don't understand why there aren't more Cardano users interested in this tool), I will reconsider. 

Best way to get there is to promote this tool around you !

And thanks again @rphair for your support and all your ideas helping me release this tool.

**Comment by pixelsoup42** [comment]
I will close this issue for now as there are too few users to justify investing time in this tool.

If more people chime in (I don't understand why there aren't more Cardano users interested in this tool), I will reconsider.

Best way to get there is to promote this tool around you !

And thanks again @rphair for your support and all your ideas helping me release this tool.

**Comment by rphair** [comment]
Maybe you could make it more obvious the community & call it something bone-head simply & obvious like (a shorter version of) "Cardano Asset Spreadsheet" 😅 and then re-introduce it on the Cardano Forum.  I'll back you up there to say I use it myself & am happy with it!
